### PR TITLE
Update SimpleLsThing.get_by_code API.

### PR DESCRIPTION
**Pull request by iamanandkr**
### Issue
Querying `SimpleLsThing.get_by_code` with an invalid code name, ls type or ls kind raises the following error,
```
File ~/.venvs/acasclient.ve/lib/python3.9/site-packages/acasclient-0.1.35-py3.9.egg/acasclient/lsthing.py:1989, in SimpleLsThing.get_by_code(cls, code_name, client, ls_type, ls_kind)
   [1987](file:///Users/anakumar/.venvs/acasclient.ve/lib/python3.9/site-packages/acasclient-0.1.35-py3.9.egg/acasclient/lsthing.py?line=1986)     ls_kind = cls.ls_kind
   [1988](file:///Users/anakumar/.venvs/acasclient.ve/lib/python3.9/site-packages/acasclient-0.1.35-py3.9.egg/acasclient/lsthing.py?line=1987) camel_case_dict = client.get_ls_thing(ls_type, ls_kind, code_name)
-> [1989](file:///Users/anakumar/.venvs/acasclient.ve/lib/python3.9/site-packages/acasclient-0.1.35-py3.9.egg/acasclient/lsthing.py?line=1988) simple_ls_thing = cls(ls_thing=LsThing.from_camel_dict(data=camel_case_dict))
   [1990](file:///Users/anakumar/.venvs/acasclient.ve/lib/python3.9/site-packages/acasclient-0.1.35-py3.9.egg/acasclient/lsthing.py?line=1989) simple_ls_thing.set_client(client=client)
   [1991](file:///Users/anakumar/.venvs/acasclient.ve/lib/python3.9/site-packages/acasclient-0.1.35-py3.9.egg/acasclient/lsthing.py?line=1990) return simple_ls_thing

File ~/.venvs/acasclient.ve/lib/python3.9/site-packages/acasclient-0.1.35-py3.9.egg/acasclient/lsthing.py:894, in BaseModel.from_camel_dict(cls, data)
    [885](file:///Users/anakumar/.venvs/acasclient.ve/lib/python3.9/site-packages/acasclient-0.1.35-py3.9.egg/acasclient/lsthing.py?line=884) @classmethod
    [886](file:///Users/anakumar/.venvs/acasclient.ve/lib/python3.9/site-packages/acasclient-0.1.35-py3.9.egg/acasclient/lsthing.py?line=885) def from_camel_dict(cls, data):
    [887](file:///Users/anakumar/.venvs/acasclient.ve/lib/python3.9/site-packages/acasclient-0.1.35-py3.9.egg/acasclient/lsthing.py?line=886)     """Construct an AbstractModel object from a camelCase dict
    [888](file:///Users/anakumar/.venvs/acasclient.ve/lib/python3.9/site-packages/acasclient-0.1.35-py3.9.egg/acasclient/lsthing.py?line=887) 
    [889](file:///Users/anakumar/.venvs/acasclient.ve/lib/python3.9/site-packages/acasclient-0.1.35-py3.9.egg/acasclient/lsthing.py?line=888)     :param data: dict of attributes
   (...)
    [892](file:///Users/anakumar/.venvs/acasclient.ve/lib/python3.9/site-packages/acasclient-0.1.35-py3.9.egg/acasclient/lsthing.py?line=891)     :rtype: AbstractModel
    [893](file:///Users/anakumar/.venvs/acasclient.ve/lib/python3.9/site-packages/acasclient-0.1.35-py3.9.egg/acasclient/lsthing.py?line=892)     """
--> [894](file:///Users/anakumar/.venvs/acasclient.ve/lib/python3.9/site-packages/acasclient-0.1.35-py3.9.egg/acasclient/lsthing.py?line=893)     snake_case_dict = convert_json(data, camel_to_underscore)
    [895](file:///Users/anakumar/.venvs/acasclient.ve/lib/python3.9/site-packages/acasclient-0.1.35-py3.9.egg/acasclient/lsthing.py?line=894)     return cls.from_dict(snake_case_dict)

File ~/.venvs/acasclient.ve/lib/python3.9/site-packages/acasclient-0.1.35-py3.9.egg/acasclient/lsthing.py:77, in convert_json(data, convert)
     [74](file:///Users/anakumar/.venvs/acasclient.ve/lib/python3.9/site-packages/acasclient-0.1.35-py3.9.egg/acasclient/lsthing.py?line=73)         new_data[convert(key)] = convert_json(val, convert) if (
     [75](file:///Users/anakumar/.venvs/acasclient.ve/lib/python3.9/site-packages/acasclient-0.1.35-py3.9.egg/acasclient/lsthing.py?line=74)             isinstance(val, dict) or isinstance(val, list)) else val
     [76](file:///Users/anakumar/.venvs/acasclient.ve/lib/python3.9/site-packages/acasclient-0.1.35-py3.9.egg/acasclient/lsthing.py?line=75) else:
---> [77](file:///Users/anakumar/.venvs/acasclient.ve/lib/python3.9/site-packages/acasclient-0.1.35-py3.9.egg/acasclient/lsthing.py?line=76)     raise ValueError(
     [78](file:///Users/anakumar/.venvs/acasclient.ve/lib/python3.9/site-packages/acasclient-0.1.35-py3.9.egg/acasclient/lsthing.py?line=77)         "Cannot convert {} to JSON: {}".format(type(data), data))
     [79](file:///Users/anakumar/.venvs/acasclient.ve/lib/python3.9/site-packages/acasclient-0.1.35-py3.9.egg/acasclient/lsthing.py?line=78) return new_data

ValueError: Cannot convert <class 'NoneType'> to JSON: None
```
Here the error message doesn't illustrate the problem.

### Bug
`SimpleLsThing.get_by_code` calls `acasclient.client.get_ls_thing` which returns `None` if the server encountered an internal error when fulfilling the request and because we try to create a `SimpleLsThing` object out of the `None` value we get the traceback.

### Fix
If no lsthing data was found, we raise a `KeyError` with a custom message.

## How Has This Been Tested?
- TDD.

### CODE REVIEW

**Review by dalejerikson — APPROVED** [review]
Seems straight forward but I'll wait for other reviewers to bring up anything additional that they want to discuss :)

**Review by brianbolt — APPROVED** [review]
LGTM.  

Some notes on things I see here: 
ACAS should probably throw a 200 error with an empty response body or specific response body associated with not finding an object.  I note that the persistence layer is returning a 404 error and a response body of:

```
[
acas_1       |   {
acas_1       |     errorLevel: 'error',
acas_1       |     message: 'lsThing:hi not found'
acas_1       |   }
acas_1       | ]
```
The node layer then just detects a non-200 status code from roo and throws a 500:
https://github.com/mcneilco/acas/blob/b3c76b61c2df919f3736bd17c8dd63d61e6930c4/modules/ServerAPI/src/server/routes/ThingServiceRoutes.coffee#L349

I think it's too much to fix as part of this PR to change that behavior because there are probably lots of code that response.

BTW, just for educational purposes acasclient code calls this ACAS route: https://github.com/mcneilco/acas/blob/b3c76b61c2df919f3736bd17c8dd63d61e6930c4/modules/ServerAPI/src/server/routes/ThingServiceRoutes.coffee#L5

Which calls ` exports.thingByCodeName`
Which calls the thing that is eventually messing up the response from the persistence layer and throwing a 500: https://github.com/mcneilco/acas/blob/b3c76b61c2df919f3736bd17c8dd63d61e6930c4/modules/ServerAPI/src/server/routes/ThingServiceRoutes.coffee#L272

**Review by bffrost — APPROVED** [review]
LGTM, seconding Brian's commentary

**Comment by iamanandkr** [comment]
Thank you @brianbolt, It was a great walkthrough!

**Pull request merged**
